/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Board: typeof import('./components/Board.vue')['default']
    Cell: typeof import('./components/Cell.vue')['default']
    TicTacToe: typeof import('./components/TicTacToe.vue')['default']
  }
}
